import { UserProfile, CampfirePost, MemoryItem, SecretFriendAssignment, GuessWhoGame, BadgeItem, MilestoneItem } from "@/types";

export const MOCK_CURRENT_USER: UserProfile = {
  id: "user-fanilo",
  name: "Fanilo",
  email: "fanilo@coderdojo.mg",
  avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnY27tF1psmB7nUzX-kSEmd76nTuzC9Jl9pcZFTDb6O9-9JwaX58JYdcGct3SJvJfle5QGhdrl7Vk_e1qs5T6tBT9GVg8LDFoy0VxZEOGD0PqbrcaL4_R6veDy4k0y3-Q1HlRyLWC7X9G9mwpHzaQp2d6nipxFNe-JkQqUEv56Fi0qtxpn0QG9qmsHHqHl0z3U-EKB3P3DhR8WXgh2W702zkujOICGyevjyMVL-XZsc9AfuJRbqwJ3",
  bio: "Full Stack Developer & Lead Mentor at CoderDojo Fianarantsoa. Passionate about empowering youth through code.",
  skills: ["React", "Firebase", "Python", "AI"],
  role: "ADMIN",
  status: "APPROVED",
  xp: 3500,
  level: 8,
  badges: ["badge-1", "badge-2", "badge-4"],
  workshopsCount: 25,
  studentsCount: 300,
  memoriesCount: 18,
  createdAt: "2024-01-15",
};

export const MOCK_MENTORS: UserProfile[] = [
  MOCK_CURRENT_USER,
  {
    id: "user-sarah",
    name: "Sarah Jenkins",
    email: "sarah@coderdojo.mg",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAKGjRSj4V8TlIfLEfePudYN-jTjqFV4dUvkBcPYTAy8muMnFDTjMh0N-Xy9DcpQxd2wUHcBixJmJ7qE8kLtpDM_SzPTpEJQ1m61TJwPH5mVwk0Wu6aGxiQv5YekzASZbKCSVrIkxDUgpnt9lnXwZxcHYZCPHD7ow416IKpWOAiy2ISmWaGc07CsRkyc2cj_DhQZHX_5oZ0bpS-lFd-mqGR2L0qw8M9BM4v0Rn1HWtBzwnEq4m8VW5k",
    bio: "UX/UI Designer & Scratch Instructor. Making code beautiful and accessible.",
    skills: ["Figma", "Prototyping", "CSS", "Design"],
    role: "MENTOR",
    status: "APPROVED",
    xp: 8500,
    level: 9,
    badges: ["badge-1", "badge-3"],
    workshopsCount: 18,
    studentsCount: 220,
    memoriesCount: 12,
    createdAt: "2024-02-10",
  },
  {
    id: "user-marc",
    name: "Marc Dubois",
    email: "marc@coderdojo.mg",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBDtsA9rljy5BbG3wMsgbW2htpvhDO_PqhylwQ09kufVEk86UW5R3yhnBUFalBxnUFkomtZr4zBYLyFUit1k6x20qL-jicfsN6dYGuIOtwt3fCq0i-5LwO__eKfTcLtg2TpMp1irTka1zaUdJ5O1VDNo09EFI-dyVInLQgjtTnoM1qHpKN1fNqIKSJq4GgTpnEuQCGFhLTd-ymlVVr9JSeF28fYA5VW8FCpVLPP0zXUKjdcHffGj_tg",
    bio: "Data Scientist & Python mentor. Passionate about machine learning and turtle graphics.",
    skills: ["Python", "Machine Learning", "SQL", "Robotics"],
    role: "MENTOR",
    status: "APPROVED",
    xp: 7200,
    level: 7,
    badges: ["badge-1", "badge-4"],
    workshopsCount: 14,
    studentsCount: 180,
    memoriesCount: 9,
    createdAt: "2024-03-01",
  },
  {
    id: "user-elena",
    name: "Elena Rodriguez",
    email: "elena@coderdojo.mg",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuABdT7pcBiQy8xGvAZEFo2RIyql3waCF9u4aaihebdcRocJ1ArR7tQvLf-35mauZ0eMtZbfh3DfMmyyHa5xjAcA2eUnIrstv_lKMGfH-75B3FeyMiK3JwyV9pK6Cho8dIHzpCkFRguMzz-t_Ce7cqKx5wmpBGYe94SMe3KGTkwQATVhVROqc5TTfIycOw8yr60Gj2FPXBinUS8ZsPyvt3crBKHdNg9xJMpRCdMzYNPg9CO8VA9kNUE2",
    bio: "Python & AI Enthusiast. Building the next generation of coders.",
    skills: ["Python", "AI", "Algorithms", "Web"],
    role: "MENTOR",
    status: "APPROVED",
    xp: 6400,
    level: 12,
    badges: ["badge-1", "badge-2", "badge-3", "badge-4"],
    workshopsCount: 25,
    studentsCount: 300,
    memoriesCount: 18,
    createdAt: "2023-11-20",
  },
  {
    id: "user-hery",
    name: "Hery Rajaonarivelo",
    email: "hery@coderdojo.mg",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnY27tF1psmB7nUzX-kSEmd76nTuzC9Jl9pcZFTDb6O9-9JwaX58JYdcGct3SJvJfle5QGhdrl7Vk_e1qs5T6tBT9GVg8LDFoy0VxZEOGD0PqbrcaL4_R6veDy4k0y3-Q1HlRyLWC7X9G9mwpHzaQp2d6nipxFNe-JkQqUEv56Fi0qtxpn0QG9qmsHHqHl0z3U-EKB3P3DhR8WXgh2W702zkujOICGyevjyMVL-XZsc9AfuJRbqwJ3",
    bio: "Nouvel inscrit souhaitant animer les ateliers Web & HTML/CSS.",
    skills: ["HTML", "CSS", "JavaScript"],
    role: "MENTOR",
    status: "PENDING",
    xp: 100,
    level: 1,
    badges: [],
    workshopsCount: 0,
    studentsCount: 0,
    memoriesCount: 0,
    createdAt: "2026-08-06",
  },
];

export const MOCK_POSTS: CampfirePost[] = [
  {
    id: "post-1",
    authorId: "user-sarah",
    authorName: "Sarah Jenkins",
    authorAvatar: MOCK_MENTORS[1].avatar,
    content: "Quel projet aimerais-tu créer avec les élèves la semaine prochaine ? Je pensais à un petit jeu vidéo sur Scratch, mais je suis ouverte aux idées !",
    category: "project",
    reactions: { "❤️": ["user-fanilo", "user-marc"], "💡": ["user-elena"] },
    likesCount: 12,
    commentsCount: 4,
    createdAt: "Il y a 2 heures",
  },
  {
    id: "post-2",
    authorId: "user-marc",
    authorName: "Marc Dubois",
    authorAvatar: MOCK_MENTORS[2].avatar,
    content: "Found this amazing resource for teaching basic Python loops. It uses a visual turtle graphic approach that the kids seemed to really click with today.",
    category: "teaching",
    reactions: { "🔥": ["user-fanilo", "user-sarah"], "👏": ["user-elena"] },
    likesCount: 24,
    commentsCount: 8,
    linkPreview: {
      title: "Python Turtle for Beginners",
      description: "Interactive visual programming resource.",
      url: "https://python.org/turtle",
    },
    createdAt: "Il y a 5 heures",
  },
];

export const MOCK_MEMORIES: MemoryItem[] = [
  {
    id: "mem-1",
    title: "Dev Kilonga Hackathon 2026",
    description: "What an incredible weekend! Over 50 young coders came together to build solutions for their local communities. The energy, the creativity, and the teamwork were simply unmatched. So proud of every single participant.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBy-Ipl7nNgOhUj9z2rbd6YxjH4ABAYA-lini3jVRLaOE45OMLyZYsaPDScum1NMyvqb68625o5OuKWUHFLuySFqn2-96faUrsM78t1GUNFbWYND04TGL1uL2Kf-YyMI1j8dWVhpKj6c1AJMCKccoCNi9xATyQEJ8piRDj85hLQOz68osGs9T8eLxC0ZXBVMq8kPa_pljj7f2f__tWUsoVunHEM-CIBP-aPWj5TMjk_paoCRrwjbp9i",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBy-Ipl7nNgOhUj9z2rbd6YxjH4ABAYA-lini3jVRLaOE45OMLyZYsaPDScum1NMyvqb68625o5OuKWUHFLuySFqn2-96faUrsM78t1GUNFbWYND04TGL1uL2Kf-YyMI1j8dWVhpKj6c1AJMCKccoCNi9xATyQEJ8piRDj85hLQOz68osGs9T8eLxC0ZXBVMq8kPa_pljj7f2f__tWUsoVunHEM-CIBP-aPWj5TMjk_paoCRrwjbp9i",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAKGjRSj4V8TlIfLEfePudYN-jTjqFV4dUvkBcPYTAy8muMnFDTjMh0N-Xy9DcpQxd2wUHcBixJmJ7qE8kLtpDM_SzPTpEJQ1m61TJwPH5mVwk0Wu6aGxiQv5YekzASZbKCSVrIkxDUgpnt9lnXwZxcHYZCPHD7ow416IKpWOAiy2ISmWaGc07CsRkyc2cj_DhQZHX_5oZ0bpS-lFd-mqGR2L0qw8M9BM4v0Rn1HWtBzwnEq4m8VW5k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBDtsA9rljy5BbG3wMsgbW2htpvhDO_PqhylwQ09kufVEk86UW5R3yhnBUFalBxnUFkomtZr4zBYLyFUit1k6x20qL-jicfsN6dYGuIOtwt3fCq0i-5LwO__eKfTcLtg2TpMp1irTka1zaUdJ5O1VDNo09EFI-dyVInLQgjtTnoM1qHpKN1fNqIKSJq4GgTpnEuQCGFhLTd-ymlVVr9JSeF28fYA5VW8FCpVLPP0zXUKjdcHffGj_tg",
    ],
    authorId: "user-elena",
    authorName: "Alex Mercer",
    authorAvatar: MOCK_MENTORS[3].avatar,
    authorRole: "Lead Mentor",
    eventDate: "Déc 2026",
    likesCount: 24,
    commentsCount: 8,
    reactions: { "❤️": ["user-fanilo", "user-sarah"] },
    createdAt: "2026-12-01",
  },
  {
    id: "mem-2",
    title: "Python Fundamentals Workshop",
    description: "First steps into variables and loops. Seeing the 'aha!' moments is always the best part of being a mentor.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAKGjRSj4V8TlIfLEfePudYN-jTjqFV4dUvkBcPYTAy8muMnFDTjMh0N-Xy9DcpQxd2wUHcBixJmJ7qE8kLtpDM_SzPTpEJQ1m61TJwPH5mVwk0Wu6aGxiQv5YekzASZbKCSVrIkxDUgpnt9lnXwZxcHYZCPHD7ow416IKpWOAiy2ISmWaGc07CsRkyc2cj_DhQZHX_5oZ0bpS-lFd-mqGR2L0qw8M9BM4v0Rn1HWtBzwnEq4m8VW5k",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAKGjRSj4V8TlIfLEfePudYN-jTjqFV4dUvkBcPYTAy8muMnFDTjMh0N-Xy9DcpQxd2wUHcBixJmJ7qE8kLtpDM_SzPTpEJQ1m61TJwPH5mVwk0Wu6aGxiQv5YekzASZbKCSVrIkxDUgpnt9lnXwZxcHYZCPHD7ow416IKpWOAiy2ISmWaGc07CsRkyc2cj_DhQZHX_5oZ0bpS-lFd-mqGR2L0qw8M9BM4v0Rn1HWtBzwnEq4m8VW5k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuABdT7pcBiQy8xGvAZEFo2RIyql3waCF9u4aaihebdcRocJ1ArR7tQvLf-35mauZ0eMtZbfh3DfMmyyHa5xjAcA2eUnIrstv_lKMGfH-75B3FeyMiK3JwyV9pK6Cho8dIHzpCkFRguMzz-t_Ce7cqKx5wmpBGYe94SMe3KGTkwQATVhVROqc5TTfIycOw8yr60Gj2FPXBinUS8ZsPyvt3crBKHdNg9xJMpRCdMzYNPg9CO8VA9kNUE2",
    ],
    authorId: "user-sarah",
    authorName: "Sarah J.",
    authorAvatar: MOCK_MENTORS[1].avatar,
    eventDate: "Nov 2026",
    likesCount: 12,
    commentsCount: 2,
    reactions: { "👏": ["user-marc"] },
    createdAt: "2026-11-15",
  },
];

export const MOCK_SECRET_FRIEND: SecretFriendAssignment = {
  id: "sf-1",
  campaignId: "camp-autumn-2023",
  mentorId: "user-fanilo",
  secretFriendId: "user-sarah",
  secretFriendName: "Sarah Jenkins",
  secretFriendAvatar: MOCK_MENTORS[1].avatar,
  missionTitle: "Mission de la semaine",
  missionDescription: '"Envoyer un message positif cette semaine"',
  completed: false,
  actionJournal: [
    {
      id: "act-1",
      actionText: "Tu as laissé un mot d'encouragement sur son bureau.",
      timeAgo: "Il y a 3 jours",
      icon: "favorite",
    },
    {
      id: "act-2",
      actionText: "Tu as offert un café virtuel.",
      timeAgo: "Semaine dernière",
      icon: "local_cafe",
    },
  ],
};

export const MOCK_GUESS_WHO: GuessWhoGame = {
  id: "gw-1",
  clue: '"J\'ai appris Python pendant le confinement"',
  targetMentorId: "user-tahina",
  targetMentorName: "Tahina",
  options: [
    { id: "user-fanilo", name: "Fanilo", avatar: MOCK_CURRENT_USER.avatar },
    { id: "user-tahina", name: "Tahina", avatar: MOCK_MENTORS[1].avatar },
    { id: "user-mamy", name: "Mamy", avatar: MOCK_MENTORS[2].avatar },
  ],
  active: true,
  createdAt: "2026-08-01",
};

export const MOCK_BADGES: BadgeItem[] = [
  {
    id: "badge-1",
    name: "Mentor engagé",
    description: "Attended 10 sessions",
    icon: "favorite",
    unlocked: true,
    unlockedAt: "2024-05-10",
  },
  {
    id: "badge-2",
    name: "Gardien des souvenirs",
    description: "Uploaded 50 photos",
    icon: "photo_camera",
    unlocked: true,
    unlockedAt: "2024-06-12",
  },
  {
    id: "badge-3",
    name: "Esprit d'équipe",
    description: "Co-mentored 5 times",
    icon: "handshake",
    unlocked: true,
    unlockedAt: "2024-07-01",
  },
  {
    id: "badge-4",
    name: "Innovateur",
    description: "Created a new workshop",
    icon: "lightbulb",
    unlocked: true,
    unlockedAt: "2024-07-20",
  },
];

export const MOCK_MILESTONES: MilestoneItem[] = [
  {
    id: "ms-1",
    title: "One Year Anniversary",
    description: "You've been an active part of the clubhouse for a full year. Thank you for your dedication!",
    icon: "workspace_premium",
    xpAwarded: 500,
    completed: true,
    completedDate: "Oct 12, 2023",
  },
  {
    id: "ms-2",
    title: "Scratch Master",
    description: "Help 20 ninjas complete their first Scratch project.",
    icon: "school",
    xpAwarded: 300,
    completed: false,
    progress: 14,
    maxProgress: 20,
  },
];
